language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t karthikmurali/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karthikmurali/docker-react npm run test